### ISSUE TITLE
How do you exactly use pui_vec::Id?

### ISSUE THREAD

**Issue by changhe3** [RustyYato/pui#2]
There's only this one implementation...
```rust
impl<I: OneShotIdentifier, V: Version> ArenaKey<I, V> for Key<Id<I::Token>, V::Save>
```
How do you exact construct an arena that satisfies the OneShotIdentifier?

**Comment by RustyYato** [comment]
Hi, sorry for the super late reply!

Checking out the docs for [OneShotIdentifier](https://docs.rs/pui-core/0.5.2/pui_core/trait.OneShotIdentifier.html) we can see that you can use
* [`pui_core::scoped::Scoped`](https://docs.rs/pui-core/0.5.2/pui_core/scoped/struct.Scoped.html) - this always works because scoped identifiers can't leak outside their scope
* [`pui_core::dynamic::Dynamic`](https://docs.rs/pui-core/0.5.2/pui_core/dynamic/struct.Dynamic.html)  - this only works if you setup the dynamic identifier without a pool (pools allow reuse, which would violate the requirements of `OneShotIdentifier`)

Here's an example of for each of them

```rs
pui_core::scoped::Scoped::with(|scope| {
    use pui_arena::Key;
    use pui_vec::Id;

    // you need the `<_, _>` here because otherwise Rust won't use the default generic parameter for the version
    let mut arena = Arena::<_, _>::with_ident(scope);
    let key: Key<Id<_>, _> = arena.insert(10);
});
```

```rs
let mut arena = Arena::<_, _>::with_ident(pui_core::dynamic::Dynamic::create());
let key: Key<Id<_>, _> = arena.insert(10);
```

Does this answer your question?

**Comment by changhe3** [comment]
I see. Thanks for your explanation.
